### ISSUE TITLE
AMO page not found

### ISSUE THREAD

**Issue by SamB** [bountysource/browser-extension#13]
When I follow the "Install Firefox Extension" link to <https://addons.mozilla.org/en-US/firefox/addon/bountysource/>, I get told "We're sorry, but we can't find what you're looking for."

**Comment by rappo** [comment]
@SamB 
We received some feedback from Mozilla and need to resubmit the extension. We hope to have it resubmitted by Wednesday. It can take a while for their review, but the extension should be available immediately after submission (just not discoverable). We'll post as soon as it's back up!

Cross-referenced with the front-end issue: https://github.com/bountysource/frontend/issues/941

**Comment by rappo** [comment]
The extension has been resubmitted and can be downloaded here: https://addons.mozilla.org/en-US/firefox/addon/bountysource/

I'll close this as soon as we get approval from Mozilla.

**Comment by rappo** [comment]
We were approved by Mozilla -- forgot to close this! :)
