### ISSUE TITLE
Direct link to bountysource URL

### ISSUE THREAD

**Issue by orschiro** [bountysource/browser-extension#61]
Hi all, 

Take the following thumb up example:

![image](https://cloud.githubusercontent.com/assets/170947/7179483/97256080-e438-11e4-9d8c-bcc5fa937ab7.png)

Is it possible to redirect the user by directly clicking onto the thumb count?

Would be very useful as a quick shortcut!

Thanks ahead!

Robert

**Comment by waldyrious** [comment]
:+1: :)

**Comment by wkonkel** [comment]
Added in d0033112d249b7934726bcafa1c766ef935c1463 and published 0.0.14 to Chrome and Firefox. Should be available soon.

**Comment by orschiro** [comment]
@wkonkel 

Thanks a lot for adding the feature! :+1:
