### ISSUE TITLE
Hide any comment with just "+1" or ":thumbsup:" [$50]

### ISSUE THREAD

**Issue by rappo** [bountysource/browser-extension#7]
Open to discussion about how to hide the comments without completely losing them

- [ ] Hide any comments with *just* "+1" or ":thumbsup:"
- [ ] Extension setting to toggle this feature
- [ ] Show a summary ("10 +1 comments were hidden. Show them.")?

* What about short comments such as "I like this! +1"?
* Should hidden comments be able to be toggled on per-issue on the issue view itself?

**Comment by vegetableman** [comment]
@rappo Would like to work on this. The README says it's supported already? which is misleading. Suggestions:-

> Hide any comments with just "+1" or ":thumbsup:"
Extension setting to toggle this feature

 - A settings tab on the popup with a checkbox to toggle such comments. Enabled (hide +1 comments) by default.

>Show a summary ("10 +1 comments were hidden. Show them.")?

 Summary of count of hidden comments could be displayed on the settings tab/end of issues page.

>What about short comments such as "I like this! +1"?

 A bunch of heuristics could be added to hide such comments. But don't think it's worth it, may lead to misnomers.  We should settle for ```+1```.

>Should hidden comments be able to be toggled on per-issue on the issue view itself?

If we settle only for ```+1``` comments, this would not be needed.

**Comment by rappo** [comment]
@vegetableman Great! I'd love to see this added :)

> A settings tab on the popup with a checkbox to toggle such comments. Enabled (hide +1 comments) by default.

In Chrome, the standard seems to be to have "Options" if you right click on the icon. This usually takes you to something like chrome-extension://<extension>/settings/settings.html. We should follow this convention. I'm not sure what the convention is for Firefox, but we should figure that out as Mozilla is relatively strict with their extension approval.

> The README says auto-hide is supported already? which seems misleading.

Correct, this is wrong. We need to update it, just haven't yet. 

> Summary of count of hidden comments could be displayed on the settings tab/end of issues page.

My suggestion is to add an event to the Issue timeline immediately after the first post. Here's a rough mockup:
![image](https://cloud.githubusercontent.com/assets/2245234/6240990/2deb2b08-b6cb-11e4-999d-a66aa1c107bd.png)

> A bunch of heuristics could be added to hide such comments. But don't think it's worth it, may lead to misnomers. We should settle for +1.

Agreed. Let's only hide comments that contain +1. I think there are three ways that +1 could appear. Plaintext, wrapped with : for the emoji, or "thumbsup" wrapped with : for the same emoji.

Here's a good test issue since there are a bunch of +1s on it: https://github.com/angular/angular.js/issues/1699

**Comment by vegetableman** [comment]
Agreed. Thanks for sharing the angular link. Working on it.

**Comment by vegetableman** [comment]
Added support for chrome. checkout #52 
Will look into firefox.

**Comment by vegetableman** [comment]
Added firefox support.

**Comment by rappo** [comment]
:+1: Thanks for the contribution!
